services:
  db:
    image: postgres:15
    restart: always
    environment:
      DATABASE_URL: postgresql://doadmin:AVNS_0m0NabkZc2oCr2yWqZV@nexacademy-do-user-16631038-0.k.db.ondigitalocean.com:25060/defaultdb?sslmode=require
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  app:
    build: .
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://doadmin:AVNS_0m0NabkZc2oCr2yWqZV@nexacademy-do-user-16631038-0.k.db.ondigitalocean.com:25060/defaultdb?sslmode=require
      NODE_ENV: production
      PRISMA_MIGRATE_SKIP_GENERATE: "true"
      PRISMA_MIGRATE_SKIP_SHADOW_DATABASE: "true"
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    command: >
      sh -c "npx prisma migrate deploy && npm run build && npm start"

volumes:
  postgres_data: 